### ISSUE TITLE
Hello, here is someone with the same idea

### ISSUE THREAD

**Issue by Chaosflo** [VarChar42/hassio-netzooe-eservice#2]
Hello or Servus =) 
I have on accident while I wanted to checkout my own repository, found yours with the same idea!

So I have a few questions about your implemenation!
First off, how did you get rid of the problem with historical data? 
As the endpoint your query only contains historical data which can not be importet into the hass that easy?

Greetings from Upper Austria
Florian

**Comment by VarChar42** [comment]
Hello,
there is no direct way of importing historical data into homeassistant. The only possibility is to connect to the database and insert historical data manually.

This integration simply queries the latest value every hour and displays it as a sensor entity.

**Comment by VarChar42** [comment]
Do you by any chance own a YT channel with 1,5M subs? 😜
