### ISSUE TITLE
Q: how to configure the addon?

### ISSUE THREAD

**Issue by mbu147** [VarChar42/hassio-netzooe-eservice#3]
Hello,

Maybe it's a stupid question and I'm just blind, but how can I configure the addon in Home Assistant?
I installed it with HACS and restarted the HA container, but I don't have an integration that I can configure from the dashboard.

Are there any examples of how I can configure it (either with configuration.yaml or through the UI)?

Thanks,

**Comment by mbu147** [comment]
@VarChar42 ping :)

**Comment by VarChar42** [comment]
This integration can be configured from the UI.

**Comment by mbu147** [comment]
Not on my instance, does this work with home assistant container or only with HASS OS?
I cannot find any integration after installation via HACS.

**Comment by VarChar42** [comment]
I just tried to set it up on a fresh install and indeed the setup flow does not show up.

**Comment by VarChar42** [comment]
I will look into it

**Comment by VarChar42** [comment]
The integration should now appear in the "Add Integration" UI.

Thanks for the report. 👍

**Comment by mbu147** [comment]
Thank you, can configure it now.
